const express = require("express")
const router = express.Router()
const employee = require('./employee')
const branch = require('./branch')
const department = require('./department')
const designation = require('./designation')
const auth = require('./auth')
const company = require('./company')
const attendence = require('./attendence')
const booking = require('./booking')
const grade = require('./grade')
const holiday = require('./holiday')
const leave = require('./leave')
const pessengerManifest = require('./passengerManifest')
const rigManifest = require('./rigManifest')
const salaryComponent = require('./salaryComponent')
const salaryGrade = require('./salaryGrade')
const salaryStructure = require('./salaryStructure')
const shift = require('./shift')
const salary = require('./salary')
const package = require('./package')
const alert = require('./alert')
const tds = require('./tds')
const candidate = require('./candiates')
const loan = require('./loan')
const employeeLoan = require('./employeeLoan')
const userAccess = require('./userAccess')
const roleMaster = require('./roleMaster')
const leaveRequest = require('./Employee_Leave')
const roster = require('./rosterRoutes')
const AttendenceSetting = require('./attendence_setting')
const AttendenceNotification = require('./attendence_Notification')
const alwaysPresent = require('./alwaysPresent')
const attendance_configuration = require('./attendance_configuration')
const LeaveConfig = require('./leave_config')
const leave_configuration = require('./leaveConfiguration')
const leaveType = require('./leaveType')
const leaveTypeConfiguration = require('./leaveTypeConfiguration')
const crew = require('./crew')
const city = require('./city')

const lateComingEarlyGoing = require('./lateComingEarlyGoing')
const overtimeApprovalNotification = require('./overtimeApprovalNotification')
const leaveApproval = require('./leaveApproval')
const config = require('./configuration')

const regularizeAttendance = require('./regularize_attendance')
const creditLeave = require('./creditLeave')
const template = require('./template')
const exitDetails = require('./exitDetails')


router.use('/employee', employee)
router.use('/branch', branch)
router.use('/department', department)
router.use('/designation', designation)
router.use('/auth', auth)
router.use('/company', company)
router.use('/attendence', attendence)
router.use('/booking', booking)
router.use('/grade', grade)
router.use('/holiday', holiday)
router.use('/leave', leave)
router.use('/pessengerManifest', pessengerManifest)
router.use('/rigManifest', rigManifest)
router.use('/salaryComponent', salaryComponent)
router.use('/salaryGrade', salaryGrade)
router.use('/salaryStructure', salaryStructure)
router.use('/shift', shift)
router.use('/salary', salary)
router.use('/package', package)
router.use('/alert', alert)
router.use('/getTds', tds)
router.use('/candiate', candidate)
router.use('/loan', loan)
router.use('/employeeLoan', employeeLoan)
router.use('/access', userAccess)
router.use('/role', roleMaster)
router.use('/leaveRequest', leaveRequest)
router.use('/roster', roster)
router.use('/AttendenceSetting', AttendenceSetting)
router.use('/attendenceNotification', AttendenceNotification)
router.use('/alwaysPresent', alwaysPresent)
router.use('/leaveConfig', LeaveConfig)
router.use('/attendanceConfiguration', attendance_configuration)
router.use('/leaveConfiguration', leave_configuration)
router.use('/leaveType', leaveType)
router.use('/leaveTypeConfiguration', leaveTypeConfiguration)
router.use('/roster',roster)
router.use('/places',city)
router.use('/crew',crew)
router.use('/lateComingEarlyGoing',lateComingEarlyGoing)
router.use('/overtimeApprovalNotification',overtimeApprovalNotification)
router.use('/leaveApproval',leaveApproval)
router.use('/roster', roster)
router.use('/places', city)
router.use('/crew', crew)
router.use('/config', config)
router.use('/regularizeAttendance',regularizeAttendance)
router.use('/creditLeave',creditLeave)
router.use('/template',template)
router.use('/exitDetail',exitDetails)

module.exports = router